# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: expenses_dev

test:
  <<: *default
  database: expenses_test

production:
  <<: *default
  database: expenses_pro
  username: root
  password: root # use an environment variable for security
